language: python
python:
  - "2.7"

# command to install dependencies
install: pip install -r requirements.txt --use-mirrors
# command to run tests
script: python test/run

notifications:
  email:
    recipients:
      - jprinc16@vols.utk.edu
    on_success: change
    on_failure: change
